language: php
php:
  - "5.4"

before_script:
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar update
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

services:
  - mongodb

script:
  - cd /tests
  - phpunit

notifications:
  email: false