language: php
php:
  - "5.4"

before_script:
  - pecl -q install mongo && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar install

services:
  - mongodb

script:
  - cd /tests
  - phpunit

notifications:
  email: false