<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Geolocation\Module'                        => __DIR__ . '/Module.php',
    'Geolocation\Document\Country'              => __DIR__ . '/src/Geolocation/Document/Country.php',
    'Geolocation\Document\Geolocation'          => __DIR__ . '/src/Geolocation/Document/Geolocation.php',
    'Geolocation\Helper\GoogleMapsHelper'       => __DIR__ . '/src/Geolocation/Helper/GoogleMapsHelper.php',
    'Geolocation\Service\GeolocationService'    => __DIR__ . '/src/Geolocation/Service/GeolocationService.php',
    'GeolocationTest\BaseTest'                  => __DIR__ . '/tests/GeolocationTest/BaseTest.php',
    'GeolocationTest\Framework\GeolocationTest' => __DIR__ . '/tests/GeolocationTest/Framework/GeolocationTest.php',
);